spring.application.name=LibraryCompanion
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
jwt.secret=Nagyon_Hosszu_Ultra_Titkos_Jelszo_Amit_Csak_Mi_Tudunk
